### ISSUE TITLE
flatpak fcitx5

### ISSUE THREAD

**Issue by madjxatw** [keaising/im-select.nvim#14]
Hi, I'm currently using flatpak fcitx5 on Ubuntu 20.04, every time the nvim is launched, I get an error message stating that "please intall `im-select` binary first, ...". Please figure out what I'm missing, the README just says that `im-select` is not required on Linux but does not cover the flatpak/appimage cases. BTW, Ubuntu 20.04 delivers fcitx5 that is not fully packaged due to some dependency restrictions.

**Comment by keaising** [comment]
Have you tried to execute `fcitx5-remote -n` in your shell or `:!fcitx5-remote -n` in nvim command mode?

Could you please provide the result?

BTW, I think you can reference https://github.com/keaising/im-select.nvim/issues/12 to debug

**Comment by madjxatw** [comment]
Sorry, the flatpak fcitx5 I installed has no this command.

**Comment by madjxatw** [comment]
I created an executable shell script at `~/.local/bin/fcitx5-remote` with the following content:

```sh
#!/bin/bash
exec flatpak run --command=fcitx5-remote org.fcitx.Fcitx5 "$@"
```

Now the error message is gone, but when I am pressing `Esc` and then `i`,  the input method stays at US keyboard instead of switching back to the input method with which I left off the Insert mode.

**Comment by keaising** [comment]
Please follow the instructions in this new manual, https://github.com/keaising/im-select.nvim/tree/29fa3404d15c71c6725fab391218df9bf4775367, the features of  `fcitx5-remote` which required by `im-select.nvim` have been listed in it.

`im-select.nvim`  only works well when all requirements meet.

**Comment by madjxatw** [comment]
I upgraded my flatpak fctix5 to 5.0.23 version from which the `fcitx5-remote` command has `-n` option. I also disabled the `FocusGained`  from the default config and now everything seems to be working well!
