### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by madjxatw** [keaising/im-select.nvim#16]
I am using Windows 11 and managing plugins via lazy.nvim. The `im-select` binary is placed along with the `nvim` binary in the same directory, it can be accessed in Command Prompt and Powershell. However, with the default config, nvim keeps spawning terminal windows once launched.

I have to remove the `"FocusGained"` from the default events to prevent nvim from spawning terminal windows:

```lua
  {
    "keaising/im-select.nvim",
    opts = {
      set_default_events = { "VimEnter", "InsertLeave", "CmdlineLeave" },
    },
    config = true
  }
```

Now a terminal windows flashes around 2~3 times on each press of `Esc`, but input method does not get switched.

BTW, I could mange to switch to the US keyboard by directly executing `:!im-select 1033`.

**Comment by keaising** [comment]
Wrong config, try this one:

```lua
    {
        "keaising/im-select.nvim",
        config = function()
            require("im_select").setup({
                set_default_events = { "VimEnter", "InsertLeave", "CmdlineLeave" },
            })
        end,
    },
```

**Comment by madjxatw** [comment]
There is no longer terminal spawning occurring, but input method (keyboard) switch still does not work.

**Comment by keaising** [comment]
Please follow my instructions.

**Comment by madjxatw** [comment]
I did it but i didn't work.

**Comment by keaising** [comment]
Please follow this instruction, without modified by yourself: https://github.com/keaising/im-select.nvim/issues/16#issuecomment-1704005154

**Comment by keaising** [comment]
Can not reproduce

**Comment by keaising** [comment]
There is another user meet similar issue on Windows, but I don't use Windows heavily and I can reproduce your issue, so I add some doc https://github.com/keaising/im-select.nvim/pull/18 which metioned your issue in README. 

If someone can fix your issues on Windows in the future, I will merge their PR.

**Comment by MasouShizuka** [comment]
Maybe you could try changing this code in `im_select.lua`:
```lua
    if C.async_switch_im then
        vim.fn.jobstart(table.concat(command, " "), { detach = true })
    else
        local jobid = vim.fn.jobstart(table.concat(command, " "), { detach = false })
        vim.fn.jobwait({ jobid }, 200)
    end
```
to:
```lua
    if C.async_switch_im then
        -- vim.fn.jobstart(table.concat(command, " "), { detach = true })
        vim.fn.jobstart(command, { detach = true })
    else
        -- local jobid = vim.fn.jobstart(table.concat(command, " "), { detach = false })
        local jobid = vim.fn.jobstart(command, { detach = false })
        vim.fn.jobwait({ jobid }, 200)
    end
```

After I did this, im-select.nvim works on windows 11.

**Comment by MasouShizuka** [comment]
Oh sorry, I found out that the reason I had to change the code to make it work is:
```lua
vim.opt.shell = "pwsh -NoLogo"
```

If comment out the above, `im-select.nvim` could work without changing the code, but a pop-up window will appear every time I press `esc`.

**Comment by keaising** [comment]
@madjxatw Could please have a try with https://github.com/keaising/im-select.nvim/pull/22 ?

I want to know whether this PR can solve your problem
