### ISSUE TITLE
async_switch_im = true will cause Neovim to crash on Windows

### ISSUE THREAD

**Issue by xarthurx** [keaising/im-select.nvim#17]
`async_switch_im = false` all fine.

But once turned on to `true` , Neovim will either crash or halt for a long time, while the cmd window keep popping up and shutdown.

**Comment by keaising** [comment]
This is the reason that I provide an option for you to turn off async.

Neovim on Windows has a lot of wired behaviors, I think I can only provide a `it works` solution.

**Comment by keaising** [comment]
If you can provide a better solution to fix this issue, PR is welcome.

**Comment by keaising** [comment]
To be honest, there are at least three users complained about this issue, but I don't even know actually reason and what senarios you meet. 
For someone `async` is ok,  for another one `sync` is ok, but I can't reproduce none of your issues, and I don't know how to descripe the issue can help you  to fix this issue.

**Comment by xarthurx** [comment]
Probably just a comment pointing to `async` param is enough. 
Or leave this issue open. 
But anyway, it depends on you.

**Comment by keaising** [comment]
Could you please give me an example about `a comment pointing to async param is enough.` ?

**Comment by xarthurx** [comment]
> Could you please give me an example about `a comment pointing to async param is enough.` ?

I submitted a PR for the Readme. Please feel free to modify it.
