### ISSUE TITLE
HI, do you know why im-select doesn't work under tmux?

### ISSUE THREAD

**Issue by nshen** [keaising/im-select.nvim#2]
HI, do you know why im-select doesn't work under tmux?

**Comment by nshen** [comment]
after `tmux kill-server` it worked.

> HI, do you know why im-select doesn't work under tmux?

**Comment by keaising** [comment]
Thank you for your solution nshen.

For someone comes from searching in the future:

After installation, you maybe need to resource your shell config to make sure the binary `im-select` is in your `$PATH`, and simplest way is restarting your shell
