### ISSUE TITLE
Switching problem in WSL

### ISSUE THREAD

**Issue by sereinrc** [keaising/im-select.nvim#21]
When I use this plugin in neovim on WSL, I encounter a issue.

- When I use the American keyboard layout in Neovim, it doesn't automatically switch the input method when entering insert mode; it remains in the American keyboard layout unless I manually switch to another layout. However, every time I exit Neovim, it returns to normal mode, which means it retains the American keyboard layout. Consequently, the issue persists the next time I use Neovim.

Could you give me some advice to avoid this issue?

my config:
```lua
 -- im-select
  {
    "keaising/im-select.nvim",
    lazy = false,
    config = function()
      require("im_select").setup {
        default_im_select = "1033",
        default_command = "im-select.exe",
        set_default_events = { "VimEnter", "FocusGained", "InsertLeave", "CmdlineLeave" },
        set_previous_events = { "InsertEnter" },
        keep_quiet_on_no_binary = false,
        async_switch_im = true,
      }
    end,
  },
```

I use Nvchad in neovim.
Does this issue relate to the Nvchad framework?

**Comment by keaising** [comment]
Do you install `im-select.exe` in your PC?

If you run `im-select.exe` in terminal, what output look like?

**Comment by sereinrc** [comment]
Sure,I install `im-select.exe` in my pc

when I run `im-select.exe` in WSL,in output 1033 or 2052

**Comment by keaising** [comment]
Have a try with option 

```lua
async_switch_im = false
```

Maybe you meet the problem described in README

**Comment by keaising** [comment]
@sereinrc Could you please have try with https://github.com/keaising/im-select.nvim/pull/22 ?

**Comment by sereinrc** [comment]
Recently, my system had some issues, and I couldn't use my preferred Linux distribution on WSL. Therefore, I gave up on the idea of switching to Chinese in Neovim.Thank you for your patience.

**Comment by keaising** [comment]
It's OK, I will close this issue if https://github.com/keaising/im-select.nvim/pull/22 works fine.
