### ISSUE TITLE
[Bug] macOS中Rime和落格输入法切换失败

### ISSUE THREAD

**Issue by raykr** [keaising/im-select.nvim#27]
问题描述：在macOS 14.4.1中，只有苹果内置的双拼输入法在切换回insert模式时可以正确唤出中文输入，而Rime和落格输入法则不行。并且查看输入法的配置中，没有正常显示。
<img width="232" alt="image" src="https://github.com/keaising/im-select.nvim/assets/10293675/e4418a35-c6db-405b-92cc-03e576e5513e">
而在terminal中通过命令行直接执行
```sh
im-select com.apple.keylayout.ABC
im-select com.logcg.inputmethod.LogInputMac3.LogInputMac3IME
```
是可以正常切换到中文输入法并输出中文，配置中也是正常的。
<img width="297" alt="image" src="https://github.com/keaising/im-select.nvim/assets/10293675/64fcc1c2-2eff-4a1f-aacb-22c24b7a3f48">

配置文件：
```lua
return {
  "keaising/im-select.nvim",
  config = function()
    require("im_select").setup({
      -- IM will be set to `default_im_select` in `normal` mode
      -- For Windows/WSL, default: "1033", aka: English US Keyboard
      -- For macOS, default: "com.apple.keylayout.ABC", aka: US
      -- For Linux, default:
      --               "keyboard-us" for Fcitx5
      --               "1" for Fcitx
      --               "xkb:us::eng" for ibus
      -- You can use `im-select` or `fcitx5-remote -n` to get the IM's name
      default_im_select = "com.apple.keylayout.ABC",

      -- Can be binary's name or binary's full path,
      -- e.g. 'im-select' or '/usr/local/bin/im-select'
      -- For Windows/WSL, default: "im-select.exe"
      -- For macOS, default: "im-select"
      -- For Linux, default: "fcitx5-remote" or "fcitx-remote" or "ibus"
      default_command = "im-select",

      -- Restore the default input method state when the following events are triggered
      set_default_events = { "VimEnter", "FocusGained", "InsertLeave", "CmdlineLeave" },

      -- Restore the previous used input method state when the following events
      -- are triggered, if you don't want to restore previous used im in Insert mode,
      -- e.g. deprecated `disable_auto_restore = 1`, just let it empty
      -- as `set_previous_events = {}`
      set_previous_events = { "InsertEnter" },

      -- Show notification about how to install executable binary when binary missed
      keep_quiet_on_no_binary = false,

      -- Async run `default_command` to switch IM or not
      async_switch_im = true,
    })
  end,
}
```

**Comment by keaising** [comment]
macOS 自带的输入法会有类似的问题吗？

我只有 Rime 和系统自带的英语输入法，测试了一下是正常的

**Comment by RayKr** [comment]
> macOS 自带的输入法会有类似的问题吗？
> 
> 我只有 Rime 和系统自带的英语输入法，测试了一下是正常的

系统自带的输入法是正常的，但是Rime我也测试了，也会出现这种情况。另外我又通过Keyboard Maestro软件设置了快捷键来切换输入法，也出现了这种情况。因此我初步怀疑这不是im-select的问题，而是macOS系统问题，我的是14.4.1，如果可以您可以先试一下对齐下系统。

**Comment by RayKr** [comment]
就哪怕是通过Keyboard Maestro设置 Set Keyboard Layout to "Squirrel - Simplified"来执行切换，也会出现这种情况。这种感觉就像是输入法切换成功了，但是配置没加载成功。

**Comment by keaising** [comment]
<img width="264" alt="image" src="https://github.com/keaising/im-select.nvim/assets/8179012/05f94cab-e74d-4b6a-b8cf-be74a9b54651">

我确实也是 14.4.1，但是没有复现，可能是 bugOS 的什么奇怪 "feature"

**Comment by QianChenglong** [comment]
在升级到14.4.1 (23E224)后，也出现了同样的问题，切换到百度输入法后，无法输入中文，应该是最近的os版本引入的bug
<img width="431" alt="image" src="https://github.com/keaising/im-select.nvim/assets/1881126/16775e59-8fb1-4c11-a8e3-3dc0f2519210">

**Comment by keaising** [comment]
你们的 Neovim 是什么版本？可以把最近的稳定版和 nightly 都试试吗？ @QianChenglong @RayKr

**Comment by QianChenglong** [comment]
> 你们的 Neovim 是什么版本？可以把最近的稳定版和 nightly 都试试吗？ @QianChenglong @RayKr

❯ nvim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1713517273

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info

最近升级macos才出现的，用im-select命令执行一样会出问题，和插件无关

**Comment by RayKr** [comment]
我的也是NVIM v0.9.5，14.4.1 (23E224)，相同问题。

**Comment by RayKr** [comment]
macOS升级到14.5的Public Beta版本也没有修复这个问题。

**Comment by bestdax** [comment]
是的，不是插件本身的瓿，我用im_select测试也出现这个问题的。

**Comment by imroc** [comment]
我也遇到了

Neovim 版本：
```bash
$ nvim --version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1724512491
Run "nvim -V1 -v" for more info
```

mac信息：
![image](https://github.com/user-attachments/assets/77ceca68-1e75-48ca-8b17-0336549c288c)

**Comment by raykr** [comment]
我现在都升级到macOS  15.0 Beta (24A5331b)了，这个问题依旧存在，大概率凉了

**Comment by keaising** [comment]
全新发布的 15.0 怎么样？是不是还存在？

我最近想到的一个办法是用 macOS 的 Accessible API 模拟用户直接去切换右上角的输入法，不用现在 im-select 了，但是我不会写 Swift。。。而且不太有时间去学，感觉要拖延了。。。

**Comment by jensenojs** [comment]
@keaising 

15下原始的输入法也不行了呀.?

```lua
-- https://github.com/daipeihust/im-select
return {
	-- should install im-select first, see
	"keaising/im-select.nvim",
	event = "InsertEnter",
	config = function()
		require("im_select").setup({})
	end,
}
```

在neovim里面, 调用`im-select com.apple.keylayout.ABC`能够从中文输入法切换到英文输入法

<img width="1231" alt="image" src="https://github.com/user-attachments/assets/921cc5ab-79f6-42a3-8b08-335eb00f8e67">

<img width="1263" alt="image" src="https://github.com/user-attachments/assets/e6570467-3a66-4efa-b988-c2f90794b283">

**Comment by jensenojs** [comment]
补充半个自动命令, 让neovim在i模式回到n模式下的时候可以做一个自动切换, vim.notify只是用来调试用的. 朋友们可以拿这个先救救急

```lua
-- Check and switch input method to English when entering Normal mode
-- should not use InsertLeave here, refer : https://vi.stackexchange.com/questions/27194/why-doesnt-autocmd-insertleave-setlocal-relativenumber-get-executed-when-i
vim.api.nvim_create_autocmd({ "ModeChanged" }, {
    pattern = "i:n,i:v",
	callback = function()
		vim.notify("开始检查输入法", vim.log.levels.INFO, {
			title = "im-select",
		})
		-- 使用 Neovim 的函数来执行系统命令
		local result = vim.fn.system("im-select")
		vim.notify("当前输入法: " .. result, vim.log.levels.INFO, {
			title = "im-select",
		})
		-- 检查结果中是否包含英文输入法的标识
		if not string.find(result, "com.apple.keylayout.ABC") then
			-- 如果不是，切换到英文输入法
			vim.fn.system("im-select com.apple.keylayout.ABC")
			vim.notify("切换到英文输入法", vim.log.levels.INFO, {
				title = "im-select",
			})
		else
			vim.notify("已经是英文输入法", vim.log.levels.INFO, {
				title = "im-select",
			})
		end
	end,
})

```

**Comment by keaising** [comment]
但是我遇到的问题是我在 command line 里使用 `im-select com.apple.keylayout.ABC` 也不能切换成功。。

**Comment by BruceChen7** [comment]
使用macism 可以完美解决这个问题

**Comment by keaising** [comment]
朋友们，我找到一个好用的输入法切换的命令行工具，它是用 Swift 实现的，看起来避免了之前的那些工具的 bug，这个问题算是解决了：https://github.com/laishulu/macism

@raykr @QianChenglong @bestdax @jensenojs

**Comment by imroc** [comment]
@keaising 表示早就用上了
```lua
return {
  "keaising/im-select.nvim",
  lazy = false,
  vscode = true,
  opts = {
    default_im_select = "com.apple.keylayout.ABC",
    default_command = "macism",
  },
}
```

**Comment by keaising** [comment]
> @keaising 表示早就用上了
> 
> ```lua
> return {
>   "keaising/im-select.nvim",
>   lazy = false,
>   vscode = true,
>   opts = {
>     default_im_select = "com.apple.keylayout.ABC",
>     default_command = "macism",
>   },
> }
> ```

现在它是默认的了。

好东西不早点拿出来分享，推出去砍了！

**Comment by wankun-tcj** [comment]
```
{
    "description": "Shift及Caps键配置：左Shift激活鼠须管中文，右Shift激活腾讯输入法，Caps激活英文",
    "manipulators": [
        {
            "from": {
                "key_code": "left_shift",
                "modifiers": { "optional": ["any"] }
            },
            "to": [{ "key_code": "left_shift" }],
            "to_if_alone": [{ "shell_command": "/opt/homebrew/bin/macism im.rime.inputmethod.Squirrel.Hans" }],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "right_shift",
                "modifiers": { "optional": ["any"] }
            },
            "to": [{ "key_code": "right_shift" }],
            "to_if_alone": [{ "shell_command": "/opt/homebrew/bin/macism com.tencent.inputmethod.wetype.pinyin" }],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "caps_lock",
                "modifiers": { "optional": ["any"] }
            },
            "to": [{ "key_code": "caps_lock" }],
            "to_if_alone": [{ "shell_command": "/opt/homebrew/bin/macism com.apple.keylayout.ABC" }],
            "type": "basic"
        }
    ]
}
```

我并不是im-select.nvim 的用户，我之前用的是一个叫做“input-source-pro”的程序做 rime，微信输入法，原生 abc 之间的切换，也遇到了一样的问题。

感谢上面分享的macism 项目。
我现在用macism + karabiner 尝试解决这个问题。
