### ISSUE TITLE
[Feature Request] Could add an option to make me customize the im-select binary file path?

### ISSUE THREAD

**Issue by Fau818** [keaising/im-select.nvim#4]
Just like this plugin [wingforth/nvim-im-select](https://github.com/wingforth/nvim-im-select), has an option named `imselectCmd`.

---

For some reason, I might open a file directly via neovim, without some environment variables.

---

Thank you for providing such a great plugin.

**Comment by keaising** [comment]
Good idea, I will add this feature in this week.

**Comment by keaising** [comment]
@Fau818 I have finished this feature, and I test it in macOS, it works like I expected. Could you please test [this feature branch](https://github.com/keaising/im-select.nvim/tree/taiga) in Windows/WSL ?

**Comment by keaising** [comment]
Looks good, merged https://github.com/keaising/im-select.nvim/pull/5

**Comment by Fau818** [comment]
Thank you for your efforts, it's working fine for me now.
I'm also using macOS, so I couldn't test it on Windows.
