### ISSUE TITLE
seems not work in search mode 

### ISSUE THREAD

**Issue by ShiChenCong** [keaising/im-select.nvim#6]
titie is summary, in normal mode, works like a charm, not work in search mode

**Comment by ShiChenCong** [comment]
```
  vim.api.nvim_create_autocmd({ "InsertLeave", "VimEnter", "CmdlineLeave" }, {
      callback = function()
        local current_select = all_trim(vim.fn.system({ C.default_command }))
        vim.api.nvim_set_var("im_select_current_im_select", current_select)

        if current_select ~= C.default_method_selected then
          vim.fn.system({ C.default_command, C.default_method_selected })
        end
      end,
  })
```
seems like need to add `CmdlineLeave`

**Comment by keaising** [comment]
Thank you, this is a case I ignored past. 

I'll take a look this weekend.

**Comment by keaising** [comment]
@ShiChenCong I have updated code command mode, you can find it in latest commit in master branch or [this link](https://github.com/keaising/im-select.nvim/commit/6799fb1933c1512a325b25bedca23653abcfd95a)

Thank you for your issue and sample code.
