### ISSUE TITLE
If enter in cmdline the language is changing

### ISSUE THREAD

**Issue by Conte777** [keaising/im-select.nvim#8]
If I want to go to cmd mode in normal mode, the language changes to the one I had in insert mode. At the same time, most of the commands in neovim are in English. I think it's worth adding a setting to the configuration that disables language change when entering cmd mode

**Comment by keaising** [comment]
OK, I will try to add this enhancement.

**Comment by keaising** [comment]
I think the addition of `CmdlineLeave` was a mistake and I have removed it, it will no longer bother you.
